# MkDocs Configuration for TFGrid Studio Documentation
site_name: TFGrid Studio
site_description: Complete development platform for ThreeFold Grid
site_author: TFGrid Studio Team
site_url: https://docs.tfgrid.studio/

# Repository
repo_name: tfgrid-studio/tfgrid-docs
repo_url: https://github.com/tfgrid-studio/tfgrid-docs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 TFGrid Studio - Apache 2.0 License

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Roboto
    code: Roboto Mono
  
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - toc:
      permalink: true

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

# Extra
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://tfgrid.studio
      name: TFGrid Studio Main Site
    - icon: fontawesome/brands/github
      link: https://github.com/tfgrid-studio
      name: TFGrid Studio on GitHub
    - icon: fontawesome/solid/comments
      link: https://github.com/orgs/tfgrid-studio/discussions
      name: Join our community
  
  version:
    provider: mike
    default: latest
  
  status:
    production: Production Ready
    planned: Coming Soon
    wip: Work in Progress

# Navigation
nav:
  - Home: index.md
  
  - Getting Started:
    - Introduction: getting-started/introduction.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Core Concepts: getting-started/concepts.md
  
  - Guides:
    - AI Agent Deployment: guides/ai-agent.md
  
  - Architecture:
    - System Overview: architecture/overview.md
    - Source Repositories: architecture/source-repos.md
  
  - Deployment Patterns:
    - Overview: patterns/overview.md
    - Single-VM Pattern: patterns/single-vm.md
    - Gateway Pattern: patterns/gateway.md
    - K3s Pattern: patterns/k3s.md
  
  - Troubleshooting:
    - Complete Guide: troubleshooting/guide.md
  
  - Development:
    - Versioning Policy: development/versioning-policy.md
    - Pattern Contract: development/pattern-contract.md
  
  - Roadmap: roadmap.md
  
  - Community:
    - Code of Conduct: community/code-of-conduct.md
    - Contributing Guide: community/contributing.md
    - Security Policy: community/security.md
  

# Google Analytics (optional - add your tracking ID)
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
